# code generated by ChatGPT, much better than what i wrote

def roman_to_integer(roman_numeral: str) -> int:
    roman_numerals = {
        "I": 1,
        "V": 5,
        "X": 10,
        "L": 50,
        "C": 100,
        "D": 500,
        "M": 1000
    }

    result = 0
    for i, c in enumerate(roman_numeral):
        if (i+1) == len(roman_numeral) or roman_numerals[c] >= roman_numerals[roman_numeral[i+1]]:
            result += roman_numerals[c]
        else:
            result -= roman_numerals[c]

    return result

tests = ('III', 'IV', 'I', 'V', 'LVIII', 'MCMXCIV', 'XIV')
for test in tests:
	print(f'{test}: {roman_to_integer(test)}')
